server:
  servlet:
    context-path: /ship
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  task:
   execution:
    pool:
      core-size: 8
      max-size: 16
      keep-alive: 60s

shipping:
  batchSize: 700
  filePath: xlsx/file.xlsx